name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build C++ code
        run: g++ main.cpp -o main

      - name: Run the program
        run: ./main

      - name: Archive executable
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: main-executable
          path: ./main
